wandb_version: 1

episodes:
  desc: null
  value: 60
dataPrefix:
  desc: null
  value: /uufs/chpc.utah.edu/common/home/u1419542/ZARA/datasets/ecqa/episodes/
trainName:
  desc: null
  value: train.jsonl
testName:
  desc: null
  value: test.jsonl
model:
  desc: null
  value: unifiedqa
size:
  desc: null
  value: 3b
dataset:
  desc: null
  value: ecqa
peft:
  desc: null
  value: false
trainPrompt:
  desc: null
  value: None
direct:
  desc: null
  value: false
numEpochs:
  desc: null
  value: 1
batchSize:
  desc: null
  value: 8
learningRate:
  desc: null
  value: 3.0e-05
savePath:
  desc: null
  value: ./model/
deepSpeedTrain:
  desc: null
  value: false
deepSpeedTest:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
do_eval:
  desc: null
  value: false
deepspeed:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688421767.607074
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      3:
      - 16
      - 23
      4: 3.11.3
      5: 0.15.4
      6: 4.29.2
      8:
      - 5
